# Generated by Django 4.2.23 on 2025-08-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='Boshqa', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='Boshqa', upload_to='books/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(),
        ),
    ]
