# Generated by Django 4.2.23 on 2025-08-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_cover_book_genre_book_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='Boshqa', upload_to='book_covers/'),
            preserve_default=False,
        ),
    ]
