# Generated by Django 4.2.23 on 2025-08-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_image_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='book_covers/default.jpg', upload_to='book_covers/'),
        ),
    ]
